name: tests

on: [ 'push', 'pull_request',  'workflow_dispatch' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Chroma CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/chroma-core/chroma/main/rust/cli/install/install.sh | bash

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer
        uses: "ramsey/composer-install@v3"        
        with:
          dependency-versions: "${{ matrix.dependency-version }}"

      - name: Run tests
        run: composer test
