name: tests

on: [ 'push', 'pull_request',  'workflow_dispatch' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Chroma CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/chroma-core/chroma/main/rust/cli/install/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Start Chroma Server
        run: chroma run tests/chroma.yaml

      - name: Run tests
        run: composer test
